### ISSUE TITLE
Runtime Crash when using abstract activities

### ISSUE THREAD

**Issue by apm-christian-dziuba** [trbnb/MvvmBase#9]
Got the following crash: 

`Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at de.trbnb.mvvmbase.MvvmBindingActivity.getViewModelClass(MvvmBindingActivity.kt:87)
       at de.trbnb.mvvmbase.MvvmBindingActivity.onCreate(MvvmBindingActivity.kt:119)
       at de.intech.main.gui.overview.OverviewActivity.onCreate(OverviewActivity.kt:52)`

OverviewActivity is an abstract activity class. Got two activity classes inheriting from this overview activity class. They both use the same ViewModel class that is provided inside the OverviewActivity. The shared ViewModel class has one constructor parameter. But removing this, was not preventing the error.

**Comment by trbnb** [comment]
That was a silly mistake by me. I released a fix with version 1.1.1.
